# Generated by Django 4.2.10 on 2024-06-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assortment', '0002_alter_categories_options_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'Product group'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product'},
        ),
    ]
