goods = [
    {
        "image": "images/goods/set of tea table and three chairs.jpg",
        "name": "Чайний столик та три стільці",
        "description": "Комплект із трьох стільців і вінтажний столик для вітальні.",
        "price": 1499.00,
    },
    {
        "image": "images/goods/set of tea table and two chairs.jpg",
        "name": "Кавовий столик",
        "description": "Набір зі столу і двох стільців у мінімалістичному стилі.",
        "price": 799.00,
    },
    {
        "image": "images/goods/double bed.jpg",
        "name": "Двоспальне ліжко",
        "description": "Ліжко двоспальне з надголовником у стилі рококо.",
        "price": 2999.00,
    },
    {
        "image": "images/goods/kitchen table 2.jpg",
        "name": "Кухонний стіл",
        "description": "Кухонный стол для готування",
        "price": 700.00,
    },
    {
        "image": "images/goods/kitchen table.jpg",
        "name": "Журнальний столик",
        "description": "Італійський журнальний столик 19 сторіччя.",
        "price": 530.00,
    },
    {
        "image": "images/goods/corner sofa.jpg",
        "name": "Кутовий диван для вітальні",
        "description": "Кутовий диван для вітальні, різний, в стилі барокко.",
        "price": 3600.00,
    },
    {
        "image": "images/goods/bedside table.jpg",
        "name": "Приліжковий столик",
        "description": "Приліжковий столик із двома висувними шухлядами.",
        "price": 455.00,
    },
    {
        "image": "images/goods/sofa.jpg",
        "name": "Диван",
        "description": "Диван для кабінету, різний, матеріал: шкіра.",
        "price": 2199.00,
    },
    {
        "image": "images/goods/office chair.jpg",
        "name": "Стілець",
        "description": "Стілець в стилі рококо 18 сторіччя.",
        "price": 830.00,
    },
    {
        "image": "images/goods/plants.jpg",
        "name": "Підставка",
        "description": "Підставка для вазона",
        "price": 399.00,
    },
    {
        "image": "images/goods/phone.jpg",
        "name": "Телефон",
        "description": "Вінтажний антикварний телефон з циферблатом.",
        "price": 1500.00,
    },
    {
        "image": "images/goods/strange table.jpg",
        "name": "Вінтажний столик",
        "description": "Португальський вінтажний дубовий столик 19 сторіччя.",
        "price": 1250.00,
    },
    {
        "image": "images/goods/set of tea table and three chairs.jpg",
        "name": "Чайний столик та три стільці",
        "description": "Комплект із трьох стільців і вінтажний столик для вітальні.",
        "price": 1499.00,
    },
]
